### ISSUE TITLE
Create DO system

### ISSUE THREAD

**Issue by beckerdown2** [kbecker0619/cwsw_evqueue_test#10]
The Stoplites need to be able to light a lamp.

Today's demo app simply uses `puts()` to annunciate each state; however, this needs to run on a Microchip MZ board that doesn't have a stdout channel, and it needs to run on the NXP Calypso exercise kit that doesn't have a stdout channel.

Vision:
* Application writes to an output channel - don't envision using events for this. Although, we could post an event simply to notify of  a change of state.
  * This output channel is part of an application-layer Actuator component.
* The Actuator writes to the board
* The board writes to the arch's DO layer.

Note: To effect maximum abstraction, and allow easy retargeting to different platforms, each layer needs to avoid being called directly - this would be a violation of task priorities. for example, let the app component write to a buffer of some sort that belongs to the board, and the board will act on it the next time its task is called.

**Comment by kbecker0619** [comment]
As part of DoD, figger outta way to make the GTK indicators work.

**Comment by kbecker0619** [comment]
Not sure if this will work out, but my current idea is to use the `SET(Symbol, value)` API as an app-level API, and the `Set(Component, Symbol, Value)` API as useful for app-level Actuator, or services-level API.

**Comment by kbecker0619** [comment]
* add `SET()` API for Red. Target is in new actuator component "app-do-lamps".
* add provision for init and task functions.

**Comment by kbecker0619** [comment]
> As part of DoD, figger outta way to make the GTK indicators work.

Done. 
* Radio buttons were totally the wrong instrument. Given the standard toolbox, a read-only Checkbutton is the indicator i'll use.
* The existing checkbuttons were set in the panel designer as "Inconsistent." Clearing that checkbox and setting the initial state to Off allowed the indicators to work as intended.
