### ISSUE TITLE
Add App-level Sensor component

### ISSUE THREAD

**Issue by kbecker0619** [kbecker0619/cwsw_evqueue_test#5]
Now that we have board-level DI working on the GTK board, that component must feed into an application-level sensor component.

Part of this reasoning is in support of Issue #2, which instructs to add app-level button handling.

**Comment by beckerdown2** [comment]
created in app folder, `app-di-buttons` component. this will be put into the proper home later.

**Comment by beckerdown2** [comment]
moved the existing event handlers related to buttons into `app-di-buttons`: press, release, stuck, unstuck.

**Comment by beckerdown2** [comment]
this concludes the initial development. expected to do incremental improvements as development continues.
