### ISSUE TITLE
Make SRE generic

### ISSUE THREAD

**Issue by beckerdown2** [kbecker0619/cwsw_evqueue_test#9]
#### Background
Currently, the 1st version of the State Machine Engine is based on reuse of a template - each State Machine must instantiate its own copy of the engine. 

This SME is a event handler and is primarily intended to be the handler for an alarm's event.

#### Problem
The problem is that the Transition Table is unique to each SME; one could, I suppose, list all state names and all transitions in one super-table, but this is not scalable beyond any but the smallest programs.

Each instantiation of a state machine should use a common / library SME, and should be able to use its own transition table.

#### Implementation Idea
This is an idea only and is not a command to take this path:

* Each SM still has its own SME, which is a normal event handler
* The current SME changes its signature to accept a new parameter, a pointer to the transition table
* Each SME is nothing more than a shell for the call to the library SME, and supplies the transition-table parameter in its call

**Comment by kbecker0619** [comment]
One significant difference between the board-level button SME and the app-level Stoplite SME, is that the button SME supports an array of buttons.

MVP might be to have the button SME to take the parameters from the current index into the array of buttons and pass those as scalars to the library SME

**Comment by kbecker0619** [comment]
The implementation idea worked well enough for now.

Noticed that in the Button SME, i'm executing a round of SM behavior for index 0, which is currently defined as No Button and thus cannot ever receive any button activity. But the MVP has been met for now.
